# Intro to Jupyter notebook

This is a Jupyter notebook. You can think of it like a website you can edit. Most importantly, this notebook will let you run Python code, which is what we'll be doing today!

Python is an incredibly popular and useful programming language. We'll try to show you some of what it can do in this class as we build games, draw pictures, and make plots. Today, though, we need do some of the fundamentals. Once those are under your belt, your imagination is the limit with Python!

The first step to writing some Python is to interact with a cell like the one below:

If you click on the cell above, to the right of "\[  \]", you'll be able to write inside it. To "run" the cell, click on it, then hit "shift" and "return" together (or "shift" and "enter"). You can also hit the play button to the left of the cell.

### Printing

Try running the cell below, where it says, "Hello, world!"

In [ ]:
print("Hello, world!")

Hello, world!

Once you've run the cell, you should see a line with the text "Hello, world!" appear below the cell. Congrats, you've run your first line of Python!

When you run a Jupyter notebooks cell, like you just did, Python will execute all the code you've provided in the cell. Once Python finishes running your code, the cell is completed, and Python will stop.

Above, we asked Python to print "Hello, world!" When we use `print` followed by parenthesis, whatever is between the paranthesis will appear below the cell.

*Note: For words or text, you also need to put what you want to say inbetween quotation marks. This tells Python that it's dealing with something known as a `string`, but we'll get to that in more detail later.*

Let's try it. Run the next two code cells:

In [ ]:
print(4)

In [ ]:
print("Hi!")

Python will also let us print the result of math problems:

In [ ]:
print(2 + 3)

In [ ]:
print(2 * 5)

The asterisk '*' above represents multiplication.

We can even do fancier calculations:

In [ ]:
print(3 * 9 + 9 / 3)

30.0

Note that in the above calculation, Python will follow PEMDAS, doing the multiplication and division first, then the addition.

**Excercise**: Can you guess what the output will be when the cell below is run?

In [ ]:
print(3*(4 + 4))

24

**Exercise**: Make Python print 1, then 2, then 3, using equations only containing the number 4 and any mathemetical operations you'd like. The first one is done for you!

In [ ]:
print(4 / 4)
print()
print()

## Data types

What is a data type? In Python, a data type is the computer's way of keeping track of the kind of information being stored. 

Consider the way you might respond to the following prompts:

1. **Do you want a piece of toast?**

  This is likely answered with a yes or a no.

2. **How many cows did you see on your drive to the mountains?**

  The response here is probably a number. You can't see half a cow, so it's probably a whole number!

3. **How many liters of water does the average human drink a day?**

  This answer will also be a number, but could include a fractional part. For example, you may drink 3.5 liters of water in a day. That's a lot of water!

4. **Write one sentence explaining how life on Earth began.**

  This will be a full sentence!


In Python, we have different built-in data types that allow us to represent the responses to these sorts of questions.

### Integers
Integers are a whole numbers. For instance, 4, 5, and 10000 are integers. We can check they are integers in Python with the following:

In [ ]:
print( type(4) )

<class 'int'>

Negative whole numbers as also valid integers!

In [ ]:
print(type(-1))

<class 'int'>

Here, `type`, with parenthesis to the right, tell us the type of the data we put inside those parenthesis. Above, Python has told us that `4` is an `'int'` or integer, which is what we expected.

### Floats

Let's try out `type` on other things we've seen.

In [ ]:
print(type(2.5))

<class 'float'>

Here, Python is telling us `2.5` is a float. A float is basically any number that isn't zero after the decimal places, i.e. not a whole number.

If we try to divide two integers and the result is not a whole number, Python will make the result into a float.

In [ ]:
print(type(3 / 4))

<class 'float'>

If we add together a whole number and float, the result will also be a float:

In [ ]:
print(type(1 + 2.4))
print(1 + 2.4)

<class 'float'>
3.4

### Strings
Let's try finding the type of `"Hello, world!"`, which we printed earlier:

In [ ]:
print( type("Hello, world!") )

<class 'str'>

Here, Python is telling us that `"Hello, world!"` is a string. Strings can contain numbers, letters, spaces, or punctuation like this:

In [ ]:
print("H3llo!")

H3llo!

In [ ]:
print("So nice to meet you!")

So nice to meet you!

Notice that strings always begin and end with quotes. The quotes can be single or double, but must match:

In [ ]:
print("valid string")

valid string

In [ ]:
print('valid string')

valid string

In [ ]:
print('this will break")

SyntaxError: EOL while scanning string literal (<ipython-input-20-4b345fdda235>, line 1)

Notice that Python didn't like the last string because it began with single quotes and ended with double quotes.

**Exercise**: What will be printed when we run the following code?

In [ ]:
print(type('3'))

Strings very handily can be added together. The result is a longer string that is made up of the two strings connected together:

In [ ]:
print('thing 1 ' + 'thing 2')

thing 1 thing 2

In [ ]:
print('4' + '5')

45

Notice how, even though 4 and 5 are numbers, they are treated as strings when there are quotes around them, "4" and "5". Because they are both strings, the have the same `type`, and Python can still understand what it means to add them together.

However, this is a very different outcome from the mathematical process of 4 + 5 = 9, which only works when 4 and 5 are treated as integers. To illustrate:

In [ ]:
print(4 + 5)

9

If we try to add a string and a number, here's what happens:

In [ ]:
print(4 + '5')

TypeError: ignored

We can't add integers or floats to strings!

### Booleans

The last type of data we need to worry about is the boolean. Booleans only have two possible values, True or False.

In [ ]:
print(type(True))

<class 'bool'>

Booleans (or bools) come in handy when we went to check if something is true or false. For instance:

In [ ]:
print(5 > 3)

True

Above, `>` checks to see if the lefthand side is strictly greater than the right. Let's try checking the type of what Python is returning:

In [ ]:
print(type(5 > 3))

<class 'bool'>

Surprise, it's a bool!

`>` is not the only mathematical operation that produces a bool:

In [ ]:
print(4 >= 4)
print(3 == 2)
print(3 == 3)
print(1 < 0.5)

True
False
True
False

We can also change `True` to `False` and `False` to `True` with `not`:

In [ ]:
print(not False)
print(not True)

True
False

This will turn out to be very handy later!

The final operations we can perform on Booleans are `and` and `or`.

`and` takes two Booleans and returns `True` if both inputs are `True` but otherwise returns `False`.

In [ ]:
print('True and True is:', True and True)
print('True and False is:', True and False)
print('False and True is:', False and True)
print('False and False is:', False and False)

True and True is: True
True and False is: False
False and True is: False
False and False is: False

Here, we've used an additional trick, which is that `print` will let us print two separate things if we separate them with a comma.

`or` returns `True` if either one or both of the inputs are `True` but otherwise returns `False`.

In [ ]:
print('True or True is:', True or True)
print('True or False is:', True or False)
print('False or True is:', False or True)
print('False or False is:', False or False)

True or True is: True
True or False is: True
False or True is: True
False or False is: False


**Exercise**: What will be printed when we run this code? *Hint*: first evaluate things in paranthesis, then tackle the `and`

In [ ]:
print((not False) and (4 > 3))

## A comment on comments
In Python, a comment is text that goes in a code block but that is not run by the computer. In Python, comments begin with a hashtag. Everything after the hashtag on that line will not be run.

In [ ]:
# This is a comment. It will not be run.

## Variables

What we've learned so far is that Python can be a fancy calculator that can also add together strings, but it's much more than that. To make Python really useful, we need to get it to remember things about the past. We do this with **variables**.

Variables are just like variables from algebra. We give them a name and assign them a value like this:

In [ ]:
x = 5

Here, `x` is the variable name, and we've assigned it the value `5`. Now we can `print(x)` to see what value it holds:

In [ ]:
print(x)

5

`x` will now behave like any regular integer that we've used before:

In [ ]:
print(x + 1)

6

In [ ]:
print(20 / x)

4.0

If we like, we can check the `type` of `x`, just like we did with numbers before:

In [ ]:
print(type(x))

<class 'int'>

We can even reassign the value of `x`:

In [ ]:
x = 9
print(x)

9

**Exercise**: Guess what value `x` will have after the following code is run:

In [ ]:
x = 3
x = x + 1
print(x)

4

Note that we can safely define a variable in terms of itself. Each time we do this, we overwrite the old value of the variable with a new one.

**Exercise**: Guess what value `y` will have below:

In [ ]:
x = 3
y = x + 2
x = 5 # does changing x affect y?
print(y)

**Exercise**: Can the type of `x` change? Guess what type of data `x` will be after the following code runs:

In [ ]:
x = 3 
x = x / 2
print(type(x))

<class 'float'>

Variable names in Python can contain letters, numbers, and underscores.

In [ ]:
valid_variable_name = 1

Variable names cannot start with a number. Try running the code below:

In [ ]:
12_invalid_name = 5

SyntaxError: ignored

**Exercise**: The first six digits of the Fibonacci sequence are:

0, 1, 1, 2, 3, 5

Each element of the sequence is produced by adding together the two numbers that came just before it.

Try printing the first six numbers of the Fibonacci sequence without using any numbers except the ones defined as `fib_0` and `fib_1` below. Instead try defining new varibles in terms of the previous ones.

In [ ]:
fib_0 = 0
fib_1 = 1
fib_2 = fib_0 + fib_1
# write code that defines fib_3 and fib_4 in terms of fib_1 and fib_2

print(fib_0)
print(fib_1)
print(fib_2)
print(fib_3)
print(fib_4)